# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "PearlBee"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"


# template engine
# simple: default and very basic template engine
# template_toolkit: TT

session: "YAML"

#Logging
#logger: "file"
#log: "error"
template: "template_toolkit"
engines:
  template:
    template_toolkit:
      encoding: 'utf8'
      start_tag: '[%'
      end_tag:   '%]'
  session:
    YAML:
      session_dir: "/tmp/pearlbee"

plugins:
    DBIC:
      default:
        dsn: dbi:Pg:dbname=your_heroku_db_name;host=your_heroku_host;port=5432 
        schema_class: PearlBee::Model::Schema
        user: your_heroku_db_user 
        password: your_heroku_db_password 
        options:
          RaiseError: 1
          PrintError: 1
            #mysql_enable_utf8: 1
        

# Constants
captcha_folder :  'public/captcha/'
covers_folder:    'public/uploads/covers/'
import_folder:    'public/uploads/import/'
images_folder:    'public/uploads/images/'
images_path:      '/uploads/images' 
app_url:          'your_heroku_app_url'
email_templates:  'views/emails/'
secret:           'your_CaptchasDotNet_secret_pharase'
username:         'your_CaptchasDotNet_username'
alphabet:         'abcdefghkmnopqrstuvwxyz'
expire:            1800 

# Specifics
email_signature:       'The PearlBee Team'
default_email_sender:  'no-reply@pearlbee.com'
welcome_email_subject: 'Welcome to PearlBee!'
posts_on_page:         5
